beautysalon/urls.py
from django.contrib import admin
from django.urls import path, include
#import os
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.static import serve

from beautysalon.settings import BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': BASE_DIR / 'static/img',
        }
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls')),

    
]

main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.VisitListView.as_view(), name='visit_all'),
    path('create/', views.VisitCreateView.as_view(), name='visit_create'),
    path('<int:pk>/update/', views.VisitUpdateView.as_view(), 
            name='visit_update'),
    path('<int:pk>/delete/', views.VisitDeleteView.as_view(), 
            name='visit_delete'),

    path('services/', views.ServiceListView.as_view(), name='service_all'),
    path('service/create/', views.ServiceCreateView.as_view(), 
            name='service_create'),
    path('service/<int:pk>/update/', views.ServiceUpdateView.as_view(), 
            name='service_update'),
    path('service/<int:pk>/delete/', views.ServiceDeleteView.as_view(), 
            name='service_delete'),
]

users/urls.py
from django.urls import path

urlpatterns = [
    
]

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings


class Service(models.Model):
    name = models.CharField(_("Service name"), max_length=255)
    duration = models.DurationField(_('Duration in seconds'))
    
    def __str__(self):
        return self.name


class Visit(models.Model):
    date_time = models.DateTimeField(_("Date and time of visit"))
    client_note = models.CharField(_("Client's note"), blank=True, max_length=255)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    @property
    def end_date_time(self):
        return self.date_time + self.service.duration
    
    def __str__(self):
        return str(self.date_time)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('Email address'), unique=True)
    phone_number = PhoneNumberField(_('Phone number'), blank=True)
    masters_note = models.CharField(_("Master's note"), blank=True, max_length=255)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

main/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext as _

from main.models import Visit, Service

from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from main.widgets import TextRangeInput


class ClientVisitForm(ModelForm):
    class Meta:
        model = Visit
        exclude = ['client']
        widgets = {
            'date_time' : DateTimePickerInput(),
        }


class MasterVisitForm(ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'
        widgets = {
            'date_time' : DateTimePickerInput(),
        }


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = "__all__"
        widgets = {
            "duration": TextRangeInput(),
        }

main/views.py
from datetime import datetime

from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.conf import settings

from main.models import Visit, Service
from main.forms import ClientVisitForm, MasterVisitForm, ServiceForm
from main.utils import has_group

#---------Service---------------------------------------------------------------
class ServiceListView(ListView):
    model = Service


class ServiceCreateView(PermissionRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('main:service_all')
    permission_required = ('main.add_service',)


class ServiceUpdateView(PermissionRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('main:service_all')
    permission_required = ('main.change_service',)


class ServiceDeleteView(PermissionRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('main:service_all')
    permission_required = ('main.delete_service',)

#---------Visit-----------------------------------------------------------------
class VisitListView(ListView):
    model = Visit
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        return data


class GetQuerySetMixin:
    def get_queryset(self):
        queryset = super().get_queryset()
        if not has_group(self.request.user, settings.MASTER_GROUP_NAME):
            queryset = queryset.filter(client=self.request.user)
        return queryset


class FormValidMixin:
    exclude_object = False

    def form_valid(self, form):
        new_date_time = form.cleaned_data.get('date_time')
        new_service = form.cleaned_data.get('service')
        
        if new_date_time.date() <= datetime.now().date(): 
            form.add_error('date_time', _('Сan\'t create an entry for a past date'))
            return self.form_invalid(form)
        
        visits_date = Visit.objects.filter(date_time__date=new_date_time.date())
        if self.exclude_object:
            visits_date = visits_date.exclude(id=self.get_object().id)
            
        for visit in visits_date:
            if (visit.date_time < new_date_time < visit.end_date_time
                    or visit.date_time < (new_date_time+new_service.duration)
                        < visit.end_date_time ):
                form.add_error('date_time', _('Requested date and time are already taken'))
                return self.form_invalid(form)
        return super().form_valid(form)
    
    def get_form_class(self, *args, **kwargs):
        if has_group(self.request.user, settings.MASTER_GROUP_NAME):
            return MasterVisitForm
        else:
            return ClientVisitForm


class ExtraClientMixin:
    def form_valid(self, form):
        if not has_group(self.request.user, settings.MASTER_GROUP_NAME):
            obj = form.save(commit=False)
            obj.client = self.request.user
            obj.save()
        return super().form_valid(form)


class VisitCreateView(FormValidMixin, ExtraClientMixin, LoginRequiredMixin, CreateView):
    template_name = 'main/visit_form.html'
    success_url = reverse_lazy('main:visit_all')


class VisitUpdateView(GetQuerySetMixin, FormValidMixin, LoginRequiredMixin, UpdateView):
    model = Visit
    template_name = 'main/visit_form.html'
    success_url = reverse_lazy('main:visit_all')
    exclude_object = True


class VisitDeleteView(GetQuerySetMixin, LoginRequiredMixin, DeleteView):
    model = Visit
    success_url = reverse_lazy('main:visit_all')

users/views.py
from django.shortcuts import render

# Create your views here.

main/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head %} 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

main/templates/main/form.html
{% load django_bootstrap5 %}
<p>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
    {% with success_url=view.success_url %}
      {% bootstrap_button "Cancel" href=success_url button_class="btn btn-secondary" %}
    {% endwith %}
  </form>
</p>

main/templates/main/service_confirm_delete.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1>Delete Visit</h1>

<p>Are you sure you want to delete this service?</p>
<p>Name: {{ service.name }}</p>
<p>Duration: {{ service.duration }}</p>

<form method="POST">
  {% csrf_token %}
  {% bootstrap_button "Yes, delete" button_type="submit" button_class="btn-primary" %}
  {% with success_url=view.success_url %}
      {% bootstrap_button "Cancel" href=success_url button_class="btn btn-secondary" %}
  {% endwith %}
</form>
{% endblock %}

main/templates/main/service_form.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'main/form.css' %}">
{% endblock %}
{% block content %}
{% include 'main/form.html' %}
{% endblock content %}

main/templates/main/service_list.html
{% extends 'main/base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>Services</h1>
<p>
{% if service_list %}
<ul>
  {% for service in service_list %}
    <li>
        {{ service.name }} | {{ service.duration.seconds }}
        <div class="btn-group" role="group" aria-label="Basic example">
        {% if perms.main.change_service %}
          {% url 'main:service_update' service.id as update_url %}
          {% bootstrap_button "Edit" href=update_url button_class="btn btn-secondary" %}
        {% endif %} 
        {% if perms.main.delete_service %}
          {% url 'main:service_delete' service.id as delete_url%}
          {% bootstrap_button "Delete" href=delete_url button_class="btn btn-danger" %}
        {% endif %}
        </div>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no services in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'main:service_create' %}">Add a Service</a> |
<a href="{% url 'main:visit_all' %}">View Visits</a> |

{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'main:visit_all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'main:visit_all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

main/templates/main/text_range.html
<input type="{{ widget.type }}" 
        name="{{ widget.name }}" 
        id="text-input" 
        {% if widget.value != None %} 
            value="{{ widget.value|stringformat:'s' }}"
        {% endif %}
        {% include "django/forms/widgets/attrs.html" %}
        >
<input type="range" 
        id="range-input" 
        oninput="range2duration()" 
        max="{{widget.max_range}}" 
        step="{{widget.step}}"
        >
<script>

    function to2digits(number){
        return number.toString().padStart(2, '0');
    }

    function range2duration(){
        let range = document.getElementById("range-input");
        let text = document.getElementById("text-input");
        let seconds = range.value;
        let minutes = Math.floor(seconds / 60);
        let hours = Math.floor(minutes / 60);
        minutes = minutes % 60
        seconds = seconds % 60
        text.value = `${to2digits(hours)}:${to2digits(minutes)}:${to2digits(seconds)}`;
    }

</script>

main/templates/main/visit_confirm_delete.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load custom_tags %}
{% block content %}
<h1>Delete Visit</h1>

<p>Are you sure you want to delete this visit?</p>
<p>Date and time: {{ visit.date_time }}</p>
<p>Service: {{ visit.service }}</p>
{% if user|has_group:'Master' %}
<p>Client: {{ visit.client }}</p>
{% endif %}


<form method="POST">
  {% csrf_token %}
  {% bootstrap_button "Yes, delete" button_type="submit" button_class="btn-primary" %}
  {% with success_url=view.success_url %}
      {% bootstrap_button "Cancel" href=success_url button_class="btn btn-secondary" %}
  {% endwith %}
</form>
{% endblock %}

main/templates/main/visit_form.html
{% extends 'main/base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block head %}
{{ block.super }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
{{ form.media }}
<link rel="stylesheet" href="{% static 'main/form.css' %}">
{% endblock %}

{% block content %}
{% include 'main/form.html' %}
{% endblock content %}

main/templates/main/visit_list.html
{% extends 'main/base.html' %}
{% load django_bootstrap5 %}
{% load custom_tags %}
{% block content %}
<h1>Visits</h1>
<p>
  {% regroup visit_list by date_time.date as dates_list %}
  <ul class="list-group">
    {% for date in dates_list %}
    <li class="list-group-item">
      {{ date.grouper|date:'l, d F' }}
      <ul class="list-group list-group-flush">
          {% for visit in date.list %}
          <li class="list-group-item">
            {{ visit.date_time }}
            {% if visit.client == user or user|has_group:'Master' %}
            , {{ visit.service }}
            {% endif%}
            {% if user|has_group:'Master' %}
            , {{ visit.client }}
            {% endif %}
            <div class="btn-group" role="group" aria-label="Basic example">
              {% if visit.client == user or user|has_group:'Master' %}
                {% url 'main:visit_update' visit.id as update_url %}
                {% bootstrap_button "Edit" href=update_url button_class="btn btn-secondary" %}
                {% url 'main:visit_delete' visit.id as delete_url%}
                {% bootstrap_button "Delete" href=delete_url button_class="btn btn-danger" %}
              {% endif %}
            </div>
          </li> 
          {% endfor %}
      </ul>
      {% empty %}
      <p>There are no visits in the database.</p>
      {% endfor %}
    </li>
  </ul>

</p>
<p>
<a href="{% url 'main:visit_create' %}">Add a Visit</a> |
{% if perms.main.view_service %}
<a href="{% url 'main:service_all' %}">View Services</a> |
{% endif %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'main:visit_all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'main:visit_all' %}">Login</a>
{% endif %}
</p>
{% endblock %}